//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja.Infra.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int Id { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
